export { default as Dashboard } from './Dashboard';
export { default as Team } from './Team';
export { default as Contacts } from './Contacts';
export { default as Invoices } from './Invoices';
export { default as FormAdd } from './FromAdd/FormAdd';
export { default as Calendar } from './Calendar';
export { default as Faq } from './Faq';
export { default as BarChart } from './Bar';
export { default as PieChart } from './Pie';
export { default as LineChart } from './Line';
// export { default as GeoChart } from './Geography';
export { default as NavBar } from './TopBar';
export { default as LayoutSideBar } from './SideBar';
